const data = {
    products: [
        {
            name: 'black t-shirt',
            slug: 'black-tshirt',
            category: 'Shirts',
            image: '/images/p1.png',
            price: 12,
            countInStock: 10,
            brand: 'Nike',
            rating: 4.5,
            numReviews: 10,
            description: 'merch t-shirt',
        },
        {
            name: 'white t-shirt',
            slug: 'white-tshirt',
            category: 'Shirts',
            image: '/images/p1.png',
            price: 12,
            countInStock: 10,
            brand: 'Nike',
            rating: 4.5,
            numReviews: 10,
            description: 'merch t-shirt',
        },
        {
            name: 'black hoodie',
            slug: 'black-hoodie',
            category: 'Hoodie',
            image: '/images/p1.png',
            price: 12,
            countInStock: 10,
            brand: 'Nike',
            rating: 4.5,
            numReviews: 10,
            description: 'merch hoodie',
        },
        {
            name: 'white hoodie',
            slug: 'white-hoodie',
            category: 'Hoodie',
            image: '/images/p1.png',
            price: 12,
            countInStock: 10,
            brand: 'Nike',
            rating: 4.5,
            numReviews: 10,
            description: 'merch hoodie',
        },
        {
            name: 'black bandana',
            slug: 'black-bandana',
            category: 'misc',
            image: '/images/p1.png',
            price: 12,
            countInStock: 10,
            brand: 'Nike',
            rating: 4.5,
            numReviews: 10,
            description: 'merch bandana',
        },
        {
            name: 'white bandana',
            slug: 'white-bandana',
            category: 'misc',
            image: '/images/p1.png',
            price: 12,
            countInStock: 10,
            brand: 'Nike',
            rating: 4.5,
            numReviews: 10,
            description: 'merch bandana',
        },
        {
            name: 'candy',
            slug: 'candy',
            category: 'misc',
            image: '/images/p1.png',
            price: 12,
            countInStock: 10,
            brand: 'Nike',
            rating: 4.5,
            numReviews: 10,
            description: 'merch candy',
        },
    ],
};
export default data;
